# Generated by Django 3.2.7 on 2022-04-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
        ('product', '0004_alter_product_image'),
    ]

    operations = [
    ]
