# Generated by Django 3.2.7 on 2022-05-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isactive',
            field=models.IntegerField(null=True),
        ),
    ]
