# Generated by Django 3.2.7 on 2022-05-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='isactive',
            field=models.IntegerField(default=1),
        ),
    ]
