# Generated by Django 3.2.7 on 2022-02-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_quantity',
        ),
    ]
