# Generated by Django 3.2.7 on 2022-03-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 1), ('DONE', 2), ('CLOSE', 3)], default='OPEN', max_length=50, null=True),
        ),
    ]
